### ISSUE TITLE
corrupted traveler didnt spawn 

### ISSUE THREAD

**Issue by XoCynner** [Aiidoneus/The-Ascent-RPG-Modpack-Issues#1]
in the guide it tells you to find the runed teleporter and you a corrupted traveler will give you something, but the traveler wasnt there

**Comment by wyndman** [comment]
Went to a corrupted portal, found the traveler. So it might just have been an issue with the one portal area.

**Comment by wyndman** [comment]
Found a second one. So no bug

**Comment by Aiidoneus** [comment]
Closing!
