### ISSUE TITLE
[Suggestion] Add FTBLib/FTBUtilities

### ISSUE THREAD

**Issue by bigbluu722** [Aiidoneus/The-Ascent-RPG-Modpack-Issues#18]
Suggesting FTBUtils for homepoints, tpa, chat formatting, chunk claiming/chunk loading temporarily (mostly suggesting for /tpa and chunkloading functionality). FTBLib is needed for it as well so will be needed/why it's suggested.

https://minecraft.curseforge.com/projects/ftb-utilities
https://minecraft.curseforge.com/projects/ftblib

**Comment by Aiidoneus** [comment]
I already added it to the next version of the pack. Along with FTB Guides

**Comment by Aiidoneus** [comment]
Done
