### ISSUE TITLE
[mod suggestions] psi + addon

### ISSUE THREAD

**Issue by nathanenns** [Aiidoneus/The-Ascent-RPG-Modpack-Issues#26]
https://minecraft.curseforge.com/projects/psi?gameCategorySlug=mc-mods&projectID=241665
Psi, lots of fun creating your own custom spells

https://minecraft.curseforge.com/projects/magical-psi
overhauls the look of the items to make it more magical looking, better fitting a techless pack

**Comment by Aiidoneus** [comment]
Right now, I am not thinking of adding this. Sorry
