### ISSUE TITLE
Content suggestion

### ISSUE THREAD

**Issue by nathanenns** [Aiidoneus/The-Ascent-RPG-Modpack-Issues#35]
Although advent of ascension adds a lot, most of that mod is grindy or relies on RNG for drops (weapons)  Although we do have botania and blood magic as well, it would be nice to see some more mods that have content people can work through without getting into a situation of constantly dieing over and over to try to get better weapons or armour.

**Comment by Aiidoneus** [comment]
Welcome to RPG. I think you are missing the idea with this pack. If I started adding "more content," you start to deviate from the RPG style.

**Comment by nathanenns** [comment]
I understand the RPG side of things, but there needs to be a lot of content to keep people interested and going at it.  Even looking at the popular RPG games out there, there is far far more to do than just hack and slash.  

Just looking at activity.  When you first opened it there were many people on at a time, now there isn't.  That was a very fast drop off which needs to be addressed.
