### ISSUE TITLE
Sir Will Tank

### ISSUE THREAD

**Issue by Snackumzs** [Aiidoneus/The-Ascent-RPG-Modpack-Issues#4]
Adding Sir Will tank, mid-game item. Lava is everything because one of the only reliable way to get the best output for ores is the smeltery which means a lot of lava will be needed. Issue as of right now getting farther into the mod pack is lava is only obtainable by hand, bucket by bucket and some tanks are massive sizes.

**Comment by Aiidoneus** [comment]
Going to decide against. There really isn't a need for this.
